name: 'Push To Registry'
description: 'Push a container image to an image registry'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image:
    description: 'Name of the image to push'
    required: true
  tag:
    description: 'Tag of the image to push'
    required: false
    default: 'latest'
  registry:
    description: 'Registry where to push the image (eg. quay.io/username)'
    required: true
  username:
    description: 'Username to use as credential to authenticate to the registry'
    required: true
  password:
    description: 'Password to use as credential to authenticate to the registry'
    required: true
  tls-verify:
    description: 'Verify TLS certificates when contacting the registry'
    required: false
    default: 'true'
  
outputs:
  registry-path:
    description: 'The registry path to which the image was pushed'
runs:
  using: 'node12'
  main: 'dist/index.js'
